best_args = {
    "seq-fashionmnist": {
        "er": {
            500: {"lr": 0.1, "minibatch_size": 10, "batch_size": 10, "n_epochs": 1},
            5000: {"lr": 0.1, "minibatch_size": 10, "batch_size": 10, "n_epochs": 1},
        },
        "er_ace": {
            500: {
                "lr": 0.03,
                "minibatch_size": 10,
                "batch_size": 10,
                "optim_mom": 0,
                "optim_wd": 0,
                "n_epochs": 1,
            },
            5000: {
                "lr": 0.03,
                "minibatch_size": 10,
                "batch_size": 10,
                "optim_mom": 0,
                "optim_wd": 0,
                "n_epochs": 1,
            },
        },
        "derpp": {
            500: {
                "lr": 0.1,
                "minibatch_size": 10,
                "alpha": 0.2,
                "beta": 0.5,
                "batch_size": 10,
                "n_epochs": 1,
            },
            5000: {
                "lr": 0.1,
                "minibatch_size": 10,
                "alpha": 0.2,
                "beta": 0.5,
                "batch_size": 10,
                "n_epochs": 1,
            },
        },
        "ser": {
            500: {
                "lr": 0.1,
                "minibatch_size": 10,
                "alpha": 0.2,
                "beta": 0.2,
                "batch_size": 10,
                "n_epochs": 1,
            },
            5000: {
                "lr": 0.1,
                "minibatch_size": 10,
                "alpha": 0.2,
                "beta": 0.2,
                "batch_size": 10,
                "n_epochs": 1,
            },
        },
        "clser": {
            500: {
                "reg_weight": 1.0,
                "stable_model_update_freq": 0.9,
                "stable_model_alpha": 0.99,
                "plastic_model_update_freq": 1,
                "plastic_model_alpha": 0.99,
                "lr": 0.1,
                "minibatch_size": 10,
                "batch_size": 10,
                "n_epochs": 1,
            },
            5000: {
                "reg_weight": 1.0,
                "stable_model_update_freq": 0.8,
                "stable_model_alpha": 0.99,
                "plastic_model_update_freq": 1.0,
                "plastic_model_alpha": 0.99,
                "lr": 0.1,
                "minibatch_size": 10,
                "batch_size": 10,
                "n_epochs": 1,
            },
        },
    },
    "seq-cifar10": {
        "er": {
            500: {"lr": 0.1, "minibatch_size": 32, "batch_size": 32, "n_epochs": 50},
            5000: {"lr": 0.1, "minibatch_size": 32, "batch_size": 32, "n_epochs": 50},
        },
        "er_ace": {
            500: {"lr": 0.03, "optim_mom": 0, "optim_wd": 0},
            5000: {"lr": 0.03, "optim_mom": 0, "optim_wd": 0},
        },
        "derpp": {
            500: {
                "lr": 0.03,
                "minibatch_size": 32,
                "alpha": 0.2,
                "beta": 0.5,
                "batch_size": 32,
                "n_epochs": 50,
            },
            5000: {
                "lr": 0.03,
                "minibatch_size": 32,
                "alpha": 0.1,
                "beta": 1.0,
                "batch_size": 32,
                "n_epochs": 50,
            },
        },
        "ser": {
            500: {
                "lr": 0.03,
                "minibatch_size": 32,
                "alpha": 0.2,
                "beta": 0.2,
                "batch_size": 32,
                "n_epochs": 50,
            },
            5000: {
                "lr": 0.03,
                "minibatch_size": 32,
                "alpha": 0.2,
                "beta": 0.2,
                "batch_size": 32,
                "n_epochs": 50,
            },
        },
        "clser": {
            500: {
                "reg_weight": 0.15,
                "stable_model_update_freq": 0.1,
                "stable_model_alpha": 0.999,
                "plastic_model_update_freq": 0.9,
                "plastic_model_alpha": 0.999,
                "lr": 0.1,
                "minibatch_size": 32,
                "batch_size": 32,
                "n_epochs": 50,
            },
            5000: {
                "reg_weight": 0.15,
                "stable_model_update_freq": 0.8,
                "stable_model_alpha": 0.999,
                "plastic_model_update_freq": 1.0,
                "plastic_model_alpha": 0.999,
                "lr": 0.1,
                "minibatch_size": 32,
                "batch_size": 32,
                "n_epochs": 50,
            },
        },
    },
    "seq-cifar100": {
        "er": {
            500: {"lr": 0.1, "optim_mom": 0, "optim_wd": 0},
            5000: {"lr": 0.1, "optim_mom": 0, "optim_wd": 0},
        },
        "er_ace": {
            500: {"lr": 0.03, "optim_mom": 0, "optim_wd": 0},
            5000: {"lr": 0.03, "optim_mom": 0, "optim_wd": 0},
        },
        "derpp": {
            500: {"lr": 0.03, "optim_mom": 0, "optim_wd": 0, "alpha": 0.1, "beta": 0.5},
            5000: {
                "lr": 0.03,
                "optim_mom": 0,
                "optim_wd": 0,
                "alpha": 0.1,
                "beta": 0.5,
            },
        },
        "ser": {
            500: {
                "lr": 0.03,
                "minibatch_size": 32,
                "alpha": 0.5,
                "beta": 0.5,
                "batch_size": 32,
                "n_epochs": 50,
            },
            5000: {
                "lr": 0.03,
                "minibatch_size": 32,
                "alpha": 0.5,
                "beta": 0.5,
                "batch_size": 32,
                "n_epochs": 50,
            },
        },
        "clser": {
            500: {
                "reg_weight": 0.15,
                "stable_model_update_freq": 0.1,
                "stable_model_alpha": 0.999,
                "plastic_model_update_freq": 0.9,
                "plastic_model_alpha": 0.999,
                "lr": 0.1,
                "minibatch_size": 32,
                "batch_size": 32,
                "n_epochs": 50,
            },
            5000: {
                "reg_weight": 0.15,
                "stable_model_update_freq": 0.8,
                "stable_model_alpha": 0.999,
                "plastic_model_update_freq": 1.0,
                "plastic_model_alpha": 0.999,
                "lr": 0.1,
                "minibatch_size": 32,
                "batch_size": 32,
                "n_epochs": 50,
            },
        },
    },
    "seq-tinyimg": {
        "er": {
            500: {"lr": 0.03, "minibatch_size": 32, "batch_size": 32, "n_epochs": 100},
            5000: {"lr": 0.1, "minibatch_size": 32, "batch_size": 32, "n_epochs": 100},
        },
        "er_ace": {
            500: {"lr": 0.03, "optim_mom": 0, "optim_wd": 0},
            5000: {"lr": 0.03, "optim_mom": 0, "optim_wd": 0},
        },
        "derpp": {
            500: {
                "lr": 0.03,
                "minibatch_size": 32,
                "alpha": 0.2,
                "beta": 0.5,
                "batch_size": 32,
                "n_epochs": 100,
            },
            5000: {
                "lr": 0.03,
                "minibatch_size": 32,
                "alpha": 0.1,
                "beta": 0.5,
                "batch_size": 32,
                "n_epochs": 100,
            },
        },
        "ser": {
            500: {
                "lr": 0.03,
                "minibatch_size": 32,
                "alpha": 0.2,
                "beta": 1.0,
                "batch_size": 32,
                "n_epochs": 100,
            },
            5000: {
                "lr": 0.03,
                "minibatch_size": 32,
                "alpha": 0.2,
                "beta": 1.0,
                "batch_size": 32,
                "n_epochs": 100,
            },
        },
        "clser": {
            500: {
                "reg_weight": 0.1,
                "stable_model_update_freq": 0.05,
                "stable_model_alpha": 0.999,
                "plastic_model_update_freq": 0.08,
                "plastic_model_alpha": 0.999,
                "lr": 0.05,
                "minibatch_size": 32,
                "batch_size": 32,
                "n_epochs": 100,
            },
            5000: {
                "reg_weight": 0.1,
                "stable_model_update_freq": 0.07,
                "stable_model_alpha": 0.999,
                "plastic_model_update_freq": 0.08,
                "plastic_model_alpha": 0.999,
                "lr": 0.05,
                "minibatch_size": 32,
                "batch_size": 32,
                "n_epochs": 100,
            },
        },
    },
}
